name: Assignment8 workflow

on: [push]

jobs:
  test:
    name: Command Lines
    run-on: ubuntu-latest
    
    steps:
      -uses: actions/checkout@v1
      
      -name: running lines
          run: cd ~
          run: git clone https://github.com/exynos360/idoft
          run: cd idoft
          run: git checkout 3e2070733b75feed680553638c57b7e6ae253e1a
          run: rep ,ID,, pr-data.csv | grep -v \\[ | shuf --random-source=<(while :; do echo skurra2@gmu.edu; done) | head
          run: https://github.com/vojtechhabarta/typescript-generator,caef58bfe55a8cd1fc5d7368c19e9ff818a7b7fa,typescript-generator-core,cz.habarta.typescript.generator.TaggedUnionsTest.testTaggedUnionsWithInterfaces,ID,,,
          run: cd ~
          run: git clone https://github.com/vojtechhabarta/typescript-generator
          run: cd typescript-generator
          run: git rev-parse HEAD
          run: mvn test-compile -pl typescript-generator-core -am
          run: mvn -pl typescript-generator-core test -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces
          run: mvn -pl typescript-generator-core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces
